# GoReleaser configuration
archives:
 - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
   format: binary

builds:
  - binary: pilot
    dir: "."
    id: pilot
    main: ./main.go ./util.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64