name: Go

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
#   pull_request_target:
#     types: [assigned, opened, synchronize, reopened]

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Check commit messages
#        uses: wagoid/commitlint-github-action@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Build
        run: go build -v ./...